### PR TITLE
Link to CVA Kos Checker for not KOS pilots added

### PR DESCRIPTION
**Pull request by ppfeufer**
Added a link to the CVA KOS Checker for Pilots marked as NOT KOS to quickliy check the reason they are not KOS. Makes it easier to set the standings :-)

### CODE REVIEW

**Comment by lizthegrey** [comment]
There's usually _not_ a reason that people are not KOS since people default to not KOS, so looking at the KOS checker at most will just give you info on what the KOS tool thinks their corp/alliance is. What I could do is show the name of the corp/alliance alongside not-kos pilots, but linking to the KOS checker for each not-kos pilot is slightly noisy IMHO since it provides no extra info.

**Comment by lizthegrey** [comment]
(by the way, feel free to argue otherwise, I'm not a code fascist)

**Comment by ppfeufer** [comment]
Don't get me wrong, it was not my intent to step on your feet. If I have, I'm very sorry.

[...] What I could do is show the name of the corp/alliance alongside not-kos pilots [...]
Ya, that is exactly what I mentioned here -> https://github.com/eve-val/nrds-tools/issues/19

It makes it slightly easier to set the standings, allmost if we are in fast fleets we have not the time to take a look to the kos-checker site. So, in lack of my own python abillities, I simply added the link for a fast copy and paste. So we see, what exactly is not kos. The pilot himself, the corp or the alliance.

**Comment by lizthegrey** [comment]
If someone is not kos, then the pilot, corp, and alliance are ALL not KOS. If any one of them is KOS, they'll appear KOS.

**Comment by ppfeufer** [comment]
We simply have to deal with the standings slots.
So all what we wanted to know is, what we can set to blue in our standings. The pilot himself, if he is in a NPC-Corp (we can't set the NPC Corp to blue) or his corp, or if he is in an alliance, the alliance. Just a little hint in the line.

example:
[+] Rounon Dax (alliance: Yulai Federation)

This would help us to set the standings in time and safe standings slots.
And if there is no result in Checker, as in this case ( http://kos.cva-eve.org/?q=Tpot+Atruin ), let us know, he also coul'd be not friendly.

example:
[*] Tpot Atruin (no result)

Woul'd make it much easier and safe a lot of time in fleets.

Thanks a lot.

**Comment by lizthegrey** [comment]
Uhh, no. Please don't do that. Just because someone is not KOS yet does not mean that they are safe to be around or should be set blue. Even if someone appears with results saying 'not kos' does not mean anyone has ever talked to them about NRDS, and there may even be a KOS request pending against them!

**Comment by ppfeufer** [comment]
[...] Just because someone is not KOS yet does not mean that they are safe to be around [...]
Thats right.

But we have to find a way to mark the not kos resulting pilots/corps/alliances for our own pilots to prevent our pilots are breaking the NRDS rules. Setting them to +5 is way to get them out of the PvP Overview, where only reds (-5 and -10) and neutrals will be visible, in normal overvie we see them all. So, in a way we have to make a difference between neutrals and not kos. This is to prevent the own pilots to shoot at first and get us in diplomatical complexities and a matter for saving time in PvP if we have these extra information. Not more, but woul'd make things quite easier for us.

We consistently check our standings list for changes against the kos-checker itself. But not while we are flying in fleets. In fleets we first have to trust the results of the given tools. A complete check can be done later.

**Comment by lizthegrey** [comment]
Okay, that's fair. Unless the KOS checker is out of sync with the game though, one generally can go to the highest level that's not an NPC entity (e.g. individual pilot if in an npc corp, corp if not in an alliance, and alliance under all circumstances if the player is in an alliance).

**Comment by ppfeufer** [comment]
Thats what I'm talking about :-)

**Comment by lizthegrey** [comment]
Incidentally, 'no results' vs. 'not kos' have no special meaning -- 'no results' just means the CVA killboard has never seen a kill uploaded involving that player or corp, but has no special meaning.

Anyways, sure, I can definitely put instead of a link to the KOS checker simply text indicating the highest level entity that that player belongs to. I've always wanted to be able to get quick alliance compositions on blues in system anyways to figure out who's the majority of a friendly fleet.

**Pull request closed without merging**
